// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type Trip struct {
	ID          int64
	OwnerUserID int64
	Destination string
	StartDate   time.Time
	EndDate     time.Time
	CreatedAt   time.Time
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}
