// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trips.sql

package sqlc

import (
	"context"
	"time"
)

const createTrip = `-- name: CreateTrip :one
INSERT INTO trips (owner_user_id, destination, start_date, end_date)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_user_id, destination, start_date, end_date, created_at
`

type CreateTripParams struct {
	OwnerUserID int64
	Destination string
	StartDate   time.Time
	EndDate     time.Time
}

func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) (Trip, error) {
	row := q.db.QueryRowContext(ctx, createTrip,
		arg.OwnerUserID,
		arg.Destination,
		arg.StartDate,
		arg.EndDate,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Destination,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}

const listTripsByUser = `-- name: ListTripsByUser :many
SELECT id, owner_user_id, destination, start_date, end_date, created_at
FROM trips
WHERE owner_user_id = $1
ORDER BY start_date DESC
`

func (q *Queries) ListTripsByUser(ctx context.Context, ownerUserID int64) ([]Trip, error) {
	rows, err := q.db.QueryContext(ctx, listTripsByUser, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trip
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Destination,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
